package texts

import "fmt"

var fr = Strings{
	Error: "Erreur",

	ToolRefresh:   "Actualiser",
	ToolPdfReport: "Enregistrer le rapport PDF",
	ToolTray:      "Réduire dans la zone de notification",
	TrayShow:      "Afficher",
	TrayQuit:      "Quitter",
	Settings:      "Paramètres",
	Help:          "Aide",
	About:         "À propos",

	Categories: "Catégories",
	Category: CategoryStrings{
		Common:          "Général",
		RAM:             "Mémoire vive",
		System:          "Système",
		CPU:             "Processeur",
		Storage:         "Stockage",
		Graphics:        "Graphismes et écrans",
		Network:         "Réseau",
		PCI:             "Périphériques PCI",
		USB:             "Périphériques USB",
		Audio:           "Audio",
		Sensors:         "Capteurs",
		Battery:         "Batterie",
		PCIVendorDevice: "Fabricants/périphériques PCI",
	},

	ColName:          "Nom",
	ColValue:         "Valeur",
	ColModel:         "Modèle",
	ColSize:          "Taille",
	ColSpeed:         "Fréquence",
	ColVendorID:      "ID fabricant",
	ColDeviceID:      "ID périphérique",
	ColVendorName:    "Fabricant",
	ColDeviceName:    "Périphérique",
	VendorDeviceName: "Fabricant/périphérique",
	CPUModel:         "Modèle de processeur",
	CPUCores:         "Cœurs du processeur",
	Drive:            func(n int) string { return fmt.Sprintf("Disque %d", n) },
	GPU:              func(n int) string { return fmt.Sprintf("GPU %d", n) },
	Driver:           "Pilote",
	Loading:          "Chargement…",
	NoData:           "Aucune donnée disponible",
	CannotLoad:       func(err string) string { return "Impossible de charger les informations : " + err },

	SaveReportTitle:      "Enregistrer le rapport PDF",
	PDFFiles:             "Fichiers PDF",
	CannotCollect:        func(err string) string { return "Impossible de collecter les informations système : " + err },
	CannotGenerate:       func(err string) string { return "Impossible de créer le rapport : " + err },
	CannotOpenSaveDialog: func(err string) string { return "Impossible d'ouvrir la fenêtre d'enregistrement : " + err },
	CannotSave:           func(err string) string { return "Impossible d'enregistrer le rapport : " + err },
	SavedTo:              func(path string) string { return "Rapport enregistré dans " + path },

	AlwaysOnTop:    "Toujours au premier plan",
	Language:       "Langue :",
	LanguageSystem: "Comme dans le système",
	Theme:          "Thème :",
	ThemeDark:      "Sombre",
	ThemeLight:     "Clair",

	AboutTitle:   func(name string) string { return "À propos de " + name },
	Version:      "Version",
	Author:       "Auteur :",
	License:      "Licence :",
	VisitWebsite: "Visiter le site",
	Close:        "Fermer",

	Install: "Installer",
	InstallAsk: func(dir string) string {
		return "AltSysInfo sera copié dans " + dir + " et ajouté au menu Démarrer, au bureau et à la liste des applications installées. S'il y est déjà installé, il sera mis à jour. Les paramètres sont conservés.\n\nAltSysInfo redémarrera ensuite depuis cet emplacement."
	},
	InstallFailed: func(err string) string { return "Impossible d'installer AltSysInfo :\n\n" + err },
	Installed:     "AltSysInfo est installé",
	UninstallAsk: func(dir string) string {
		return "Supprimer AltSysInfo de cet ordinateur ?\n\nLes paramètres restent dans " + dir
	},
	UninstallRunning: "AltSysInfo est en cours d'exécution. Fermez-le et réessayez.",
	Uninstalled:      "AltSysInfo a été supprimé.",
}

var es = Strings{
	Error: "Error",

	ToolRefresh:   "Actualizar",
	ToolPdfReport: "Guardar informe PDF",
	ToolTray:      "Minimizar a la bandeja",
	TrayShow:      "Mostrar",
	TrayQuit:      "Salir",
	Settings:      "Ajustes",
	Help:          "Ayuda",
	About:         "Acerca de",

	Categories: "Categorías",
	Category: CategoryStrings{
		Common:          "General",
		RAM:             "Memoria RAM",
		System:          "Sistema",
		CPU:             "Procesador",
		Storage:         "Almacenamiento",
		Graphics:        "Gráficos y pantallas",
		Network:         "Red",
		PCI:             "Dispositivos PCI",
		USB:             "Dispositivos USB",
		Audio:           "Audio",
		Sensors:         "Sensores",
		Battery:         "Batería",
		PCIVendorDevice: "Fabricantes/dispositivos PCI",
	},

	ColName:          "Nombre",
	ColValue:         "Valor",
	ColModel:         "Modelo",
	ColSize:          "Tamaño",
	ColSpeed:         "Velocidad",
	ColVendorID:      "ID de fabricante",
	ColDeviceID:      "ID de dispositivo",
	ColVendorName:    "Fabricante",
	ColDeviceName:    "Dispositivo",
	VendorDeviceName: "Fabricante/dispositivo",
	CPUModel:         "Modelo de procesador",
	CPUCores:         "Núcleos del procesador",
	Drive:            func(n int) string { return fmt.Sprintf("Disco %d", n) },
	GPU:              func(n int) string { return fmt.Sprintf("GPU %d", n) },
	Driver:           "Controlador",
	Loading:          "Cargando…",
	NoData:           "No hay datos",
	CannotLoad:       func(err string) string { return "No se puede cargar la información: " + err },

	SaveReportTitle:      "Guardar informe PDF",
	PDFFiles:             "Archivos PDF",
	CannotCollect:        func(err string) string { return "No se puede obtener la información del sistema: " + err },
	CannotGenerate:       func(err string) string { return "No se puede crear el informe: " + err },
	CannotOpenSaveDialog: func(err string) string { return "No se puede abrir el cuadro de guardado: " + err },
	CannotSave:           func(err string) string { return "No se puede guardar el informe: " + err },
	SavedTo:              func(path string) string { return "Informe guardado en " + path },

	AlwaysOnTop:    "Siempre visible",
	Language:       "Idioma:",
	LanguageSystem: "Como en el sistema",
	Theme:          "Tema:",
	ThemeDark:      "Oscuro",
	ThemeLight:     "Claro",

	AboutTitle:   func(name string) string { return "Acerca de " + name },
	Version:      "Versión",
	Author:       "Autor:",
	License:      "Licencia:",
	VisitWebsite: "Visitar el sitio web",
	Close:        "Cerrar",

	Install: "Instalar",
	InstallAsk: func(dir string) string {
		return "AltSysInfo se copiará en " + dir + " y se añadirá al menú Inicio, al escritorio y a la lista de aplicaciones instaladas. Si ya está instalado allí, se actualizará. Los ajustes se mantienen.\n\nDespués AltSysInfo se reiniciará desde allí."
	},
	InstallFailed: func(err string) string { return "No se pudo instalar AltSysInfo:\n\n" + err },
	Installed:     "AltSysInfo está instalado",
	UninstallAsk: func(dir string) string {
		return "¿Quitar AltSysInfo de este equipo?\n\nLos ajustes se quedan en " + dir
	},
	UninstallRunning: "AltSysInfo está en ejecución. Ciérrelo e inténtelo de nuevo.",
	Uninstalled:      "AltSysInfo se ha quitado.",
}

var it = Strings{
	Error: "Errore",

	ToolRefresh:   "Aggiorna",
	ToolPdfReport: "Salva report PDF",
	ToolTray:      "Riduci nell'area di notifica",
	TrayShow:      "Mostra",
	TrayQuit:      "Esci",
	Settings:      "Impostazioni",
	Help:          "Guida",
	About:         "Informazioni",

	Categories: "Categorie",
	Category: CategoryStrings{
		Common:          "Generale",
		RAM:             "Memoria RAM",
		System:          "Sistema",
		CPU:             "Processore",
		Storage:         "Archiviazione",
		Graphics:        "Grafica e schermi",
		Network:         "Rete",
		PCI:             "Dispositivi PCI",
		USB:             "Dispositivi USB",
		Audio:           "Audio",
		Sensors:         "Sensori",
		Battery:         "Batteria",
		PCIVendorDevice: "Produttori/dispositivi PCI",
	},

	ColName:          "Nome",
	ColValue:         "Valore",
	ColModel:         "Modello",
	ColSize:          "Dimensione",
	ColSpeed:         "Frequenza",
	ColVendorID:      "ID produttore",
	ColDeviceID:      "ID dispositivo",
	ColVendorName:    "Produttore",
	ColDeviceName:    "Dispositivo",
	VendorDeviceName: "Produttore/dispositivo",
	CPUModel:         "Modello del processore",
	CPUCores:         "Core del processore",
	Drive:            func(n int) string { return fmt.Sprintf("Disco %d", n) },
	GPU:              func(n int) string { return fmt.Sprintf("GPU %d", n) },
	Driver:           "Driver",
	Loading:          "Caricamento…",
	NoData:           "Nessun dato disponibile",
	CannotLoad:       func(err string) string { return "Impossibile caricare le informazioni: " + err },

	SaveReportTitle:      "Salva report PDF",
	PDFFiles:             "File PDF",
	CannotCollect:        func(err string) string { return "Impossibile raccogliere le informazioni di sistema: " + err },
	CannotGenerate:       func(err string) string { return "Impossibile creare il report: " + err },
	CannotOpenSaveDialog: func(err string) string { return "Impossibile aprire la finestra di salvataggio: " + err },
	CannotSave:           func(err string) string { return "Impossibile salvare il report: " + err },
	SavedTo:              func(path string) string { return "Report salvato in " + path },

	AlwaysOnTop:    "Sempre in primo piano",
	Language:       "Lingua:",
	LanguageSystem: "Come nel sistema",
	Theme:          "Tema:",
	ThemeDark:      "Scuro",
	ThemeLight:     "Chiaro",

	AboutTitle:   func(name string) string { return "Informazioni su " + name },
	Version:      "Versione",
	Author:       "Autore:",
	License:      "Licenza:",
	VisitWebsite: "Visita il sito",
	Close:        "Chiudi",

	Install: "Installa",
	InstallAsk: func(dir string) string {
		return "AltSysInfo verrà copiato in " + dir + " e aggiunto al menu Start, al desktop e all'elenco delle app installate. Se è già installato lì, verrà aggiornato. Le impostazioni restano invariate.\n\nAltSysInfo si riavvierà poi da lì."
	},
	InstallFailed: func(err string) string { return "Impossibile installare AltSysInfo:\n\n" + err },
	Installed:     "AltSysInfo è installato",
	UninstallAsk: func(dir string) string {
		return "Rimuovere AltSysInfo da questo computer?\n\nLe impostazioni restano in " + dir
	},
	UninstallRunning: "AltSysInfo è in esecuzione. Chiudilo e riprova.",
	Uninstalled:      "AltSysInfo è stato rimosso.",
}

var pt = Strings{
	Error: "Erro",

	ToolRefresh:   "Atualizar",
	ToolPdfReport: "Salvar relatório PDF",
	ToolTray:      "Minimizar para a bandeja",
	TrayShow:      "Mostrar",
	TrayQuit:      "Sair",
	Settings:      "Configurações",
	Help:          "Ajuda",
	About:         "Sobre",

	Categories: "Categorias",
	Category: CategoryStrings{
		Common:          "Geral",
		RAM:             "Memória RAM",
		System:          "Sistema",
		CPU:             "Processador",
		Storage:         "Armazenamento",
		Graphics:        "Gráficos e telas",
		Network:         "Rede",
		PCI:             "Dispositivos PCI",
		USB:             "Dispositivos USB",
		Audio:           "Áudio",
		Sensors:         "Sensores",
		Battery:         "Bateria",
		PCIVendorDevice: "Fabricantes/dispositivos PCI",
	},

	ColName:          "Nome",
	ColValue:         "Valor",
	ColModel:         "Modelo",
	ColSize:          "Tamanho",
	ColSpeed:         "Velocidade",
	ColVendorID:      "ID do fabricante",
	ColDeviceID:      "ID do dispositivo",
	ColVendorName:    "Fabricante",
	ColDeviceName:    "Dispositivo",
	VendorDeviceName: "Fabricante/dispositivo",
	CPUModel:         "Modelo do processador",
	CPUCores:         "Núcleos do processador",
	Drive:            func(n int) string { return fmt.Sprintf("Disco %d", n) },
	GPU:              func(n int) string { return fmt.Sprintf("GPU %d", n) },
	Driver:           "Driver",
	Loading:          "Carregando…",
	NoData:           "Sem dados",
	CannotLoad:       func(err string) string { return "Não foi possível carregar as informações: " + err },

	SaveReportTitle:      "Salvar relatório PDF",
	PDFFiles:             "Arquivos PDF",
	CannotCollect:        func(err string) string { return "Não foi possível coletar as informações do sistema: " + err },
	CannotGenerate:       func(err string) string { return "Não foi possível criar o relatório: " + err },
	CannotOpenSaveDialog: func(err string) string { return "Não foi possível abrir a janela de salvamento: " + err },
	CannotSave:           func(err string) string { return "Não foi possível salvar o relatório: " + err },
	SavedTo:              func(path string) string { return "Relatório salvo em " + path },

	AlwaysOnTop:    "Sempre visível",
	Language:       "Idioma:",
	LanguageSystem: "Como no sistema",
	Theme:          "Tema:",
	ThemeDark:      "Escuro",
	ThemeLight:     "Claro",

	AboutTitle:   func(name string) string { return "Sobre o " + name },
	Version:      "Versão",
	Author:       "Autor:",
	License:      "Licença:",
	VisitWebsite: "Visitar o site",
	Close:        "Fechar",

	Install: "Instalar",
	InstallAsk: func(dir string) string {
		return "O AltSysInfo será copiado para " + dir + " e adicionado ao menu Iniciar, à área de trabalho e à lista de aplicativos instalados. Se já estiver instalado lá, será atualizado. As configurações são mantidas.\n\nDepois o AltSysInfo será reiniciado a partir de lá."
	},
	InstallFailed: func(err string) string { return "Não foi possível instalar o AltSysInfo:\n\n" + err },
	Installed:     "O AltSysInfo está instalado",
	UninstallAsk: func(dir string) string {
		return "Remover o AltSysInfo deste computador?\n\nAs configurações ficam em " + dir
	},
	UninstallRunning: "O AltSysInfo está em execução. Feche-o e tente novamente.",
	Uninstalled:      "O AltSysInfo foi removido.",
}
