package texts

import "fmt"

var zh = Strings{
	Error: "错误",

	ToolRefresh:   "刷新",
	ToolPdfReport: "保存 PDF 报告",
	ToolTray:      "最小化到托盘",
	TrayShow:      "显示",
	TrayQuit:      "退出",
	Settings:      "设置",
	Help:          "帮助",
	About:         "关于",

	Categories: "类别",
	Category: CategoryStrings{
		Common:          "概览",
		RAM:             "内存",
		System:          "系统",
		CPU:             "处理器",
		Storage:         "存储",
		Graphics:        "图形与显示器",
		Network:         "网络",
		PCI:             "PCI 设备",
		USB:             "USB 设备",
		Audio:           "音频",
		Sensors:         "传感器",
		Battery:         "电池",
		PCIVendorDevice: "PCI 厂商/设备",
	},

	ColName:          "名称",
	ColValue:         "值",
	ColModel:         "型号",
	ColSize:          "容量",
	ColSpeed:         "频率",
	ColVendorID:      "厂商 ID",
	ColDeviceID:      "设备 ID",
	ColVendorName:    "厂商",
	ColDeviceName:    "设备",
	VendorDeviceName: "厂商/设备名称",
	CPUModel:         "处理器型号",
	CPUCores:         "处理器核心",
	Drive:            func(n int) string { return fmt.Sprintf("磁盘 %d", n) },
	GPU:              func(n int) string { return fmt.Sprintf("显卡 %d", n) },
	Driver:           "驱动程序",
	Copied:           "已复制",
	Loading:          "正在加载…",
	NoData:           "无数据",
	CannotLoad:       func(err string) string { return "无法加载信息：" + err },

	SaveReportTitle:      "保存 PDF 报告",
	PDFFiles:             "PDF 文件",
	CannotCollect:        func(err string) string { return "无法收集系统信息：" + err },
	CannotGenerate:       func(err string) string { return "无法生成报告：" + err },
	CannotOpenSaveDialog: func(err string) string { return "无法打开保存对话框：" + err },
	CannotSave:           func(err string) string { return "无法保存报告：" + err },
	SavedTo:              func(path string) string { return "报告已保存到 " + path },

	AlwaysOnTop:    "窗口置顶",
	Language:       "语言：",
	LanguageSystem: "跟随系统",
	Theme:          "主题：",
	ThemeDark:      "深色",
	ThemeLight:     "浅色",

	AboutTitle:   func(name string) string { return "关于 " + name },
	Version:      "版本",
	Author:       "作者：",
	License:      "许可证：",
	VisitWebsite: "访问网站",
	Close:        "关闭",

	Install: "安装",
	InstallAsk: func(dir string) string {
		return "AltSysInfo 将被复制到 " + dir + "，并添加到开始菜单、桌面和已安装应用列表中。如果已经安装，则会更新。设置保持不变。\n\n然后 AltSysInfo 将从那里重新启动。"
	},
	InstallFailed: func(err string) string { return "无法安装 AltSysInfo：\n\n" + err },
	Installed:     "AltSysInfo 已安装",
	UninstallAsk: func(dir string) string {
		return "要从这台电脑上删除 AltSysInfo 吗？\n\n设置将保留在 " + dir
	},
	UninstallRunning: "AltSysInfo 正在运行。请关闭后重试。",
	Uninstalled:      "AltSysInfo 已删除。",
}

var ja = Strings{
	Error: "エラー",

	ToolRefresh:   "更新",
	ToolPdfReport: "PDF レポートを保存",
	ToolTray:      "トレイに最小化",
	TrayShow:      "表示",
	TrayQuit:      "終了",
	Settings:      "設定",
	Help:          "ヘルプ",
	About:         "バージョン情報",

	Categories: "カテゴリ",
	Category: CategoryStrings{
		Common:          "概要",
		RAM:             "メモリ",
		System:          "システム",
		CPU:             "プロセッサ",
		Storage:         "ストレージ",
		Graphics:        "グラフィックスとディスプレイ",
		Network:         "ネットワーク",
		PCI:             "PCI デバイス",
		USB:             "USB デバイス",
		Audio:           "オーディオ",
		Sensors:         "センサー",
		Battery:         "バッテリー",
		PCIVendorDevice: "PCI ベンダー/デバイス",
	},

	ColName:          "名前",
	ColValue:         "値",
	ColModel:         "モデル",
	ColSize:          "容量",
	ColSpeed:         "速度",
	ColVendorID:      "ベンダー ID",
	ColDeviceID:      "デバイス ID",
	ColVendorName:    "ベンダー",
	ColDeviceName:    "デバイス",
	VendorDeviceName: "ベンダー/デバイス名",
	CPUModel:         "プロセッサのモデル",
	CPUCores:         "プロセッサのコア数",
	Drive:            func(n int) string { return fmt.Sprintf("ディスク %d", n) },
	GPU:              func(n int) string { return fmt.Sprintf("GPU %d", n) },
	Driver:           "ドライバー",
	Copied:           "コピーしました",
	Loading:          "読み込み中…",
	NoData:           "データがありません",
	CannotLoad:       func(err string) string { return "情報を読み込めません: " + err },

	SaveReportTitle:      "PDF レポートを保存",
	PDFFiles:             "PDF ファイル",
	CannotCollect:        func(err string) string { return "システム情報を収集できません: " + err },
	CannotGenerate:       func(err string) string { return "レポートを作成できません: " + err },
	CannotOpenSaveDialog: func(err string) string { return "保存ダイアログを開けません: " + err },
	CannotSave:           func(err string) string { return "レポートを保存できません: " + err },
	SavedTo:              func(path string) string { return "レポートを保存しました: " + path },

	AlwaysOnTop:    "常に手前に表示",
	Language:       "言語:",
	LanguageSystem: "システムと同じ",
	Theme:          "テーマ:",
	ThemeDark:      "ダーク",
	ThemeLight:     "ライト",

	AboutTitle:   func(name string) string { return name + " について" },
	Version:      "バージョン",
	Author:       "作者:",
	License:      "ライセンス:",
	VisitWebsite: "Web サイトを開く",
	Close:        "閉じる",

	Install: "インストール",
	InstallAsk: func(dir string) string {
		return "AltSysInfo を " + dir + " にコピーし、スタート メニュー、デスクトップ、インストール済みアプリの一覧に追加します。すでにインストールされている場合は更新されます。設定はそのまま残ります。\n\nその後、AltSysInfo はそこから再起動します。"
	},
	InstallFailed: func(err string) string { return "AltSysInfo をインストールできませんでした:\n\n" + err },
	Installed:     "AltSysInfo がインストールされました",
	UninstallAsk: func(dir string) string {
		return "このコンピューターから AltSysInfo を削除しますか?\n\n設定は " + dir + " に残ります"
	},
	UninstallRunning: "AltSysInfo は実行中です。閉じてからもう一度お試しください。",
	Uninstalled:      "AltSysInfo を削除しました。",
}

var ko = Strings{
	Error: "오류",

	ToolRefresh:   "새로 고침",
	ToolPdfReport: "PDF 보고서 저장",
	ToolTray:      "트레이로 최소화",
	TrayShow:      "보기",
	TrayQuit:      "종료",
	Settings:      "설정",
	Help:          "도움말",
	About:         "정보",

	Categories: "범주",
	Category: CategoryStrings{
		Common:          "개요",
		RAM:             "메모리",
		System:          "시스템",
		CPU:             "프로세서",
		Storage:         "저장 장치",
		Graphics:        "그래픽 및 디스플레이",
		Network:         "네트워크",
		PCI:             "PCI 장치",
		USB:             "USB 장치",
		Audio:           "오디오",
		Sensors:         "센서",
		Battery:         "배터리",
		PCIVendorDevice: "PCI 제조사/장치",
	},

	ColName:          "이름",
	ColValue:         "값",
	ColModel:         "모델",
	ColSize:          "용량",
	ColSpeed:         "속도",
	ColVendorID:      "제조사 ID",
	ColDeviceID:      "장치 ID",
	ColVendorName:    "제조사",
	ColDeviceName:    "장치",
	VendorDeviceName: "제조사/장치 이름",
	CPUModel:         "프로세서 모델",
	CPUCores:         "프로세서 코어",
	Drive:            func(n int) string { return fmt.Sprintf("디스크 %d", n) },
	GPU:              func(n int) string { return fmt.Sprintf("GPU %d", n) },
	Driver:           "드라이버",
	Copied:           "복사했습니다",
	Loading:          "불러오는 중…",
	NoData:           "데이터 없음",
	CannotLoad:       func(err string) string { return "정보를 불러올 수 없습니다: " + err },

	SaveReportTitle:      "PDF 보고서 저장",
	PDFFiles:             "PDF 파일",
	CannotCollect:        func(err string) string { return "시스템 정보를 수집할 수 없습니다: " + err },
	CannotGenerate:       func(err string) string { return "보고서를 만들 수 없습니다: " + err },
	CannotOpenSaveDialog: func(err string) string { return "저장 대화 상자를 열 수 없습니다: " + err },
	CannotSave:           func(err string) string { return "보고서를 저장할 수 없습니다: " + err },
	SavedTo:              func(path string) string { return "보고서를 저장했습니다: " + path },

	AlwaysOnTop:    "항상 위에 표시",
	Language:       "언어:",
	LanguageSystem: "시스템 설정",
	Theme:          "테마:",
	ThemeDark:      "어둡게",
	ThemeLight:     "밝게",

	AboutTitle:   func(name string) string { return name + " 정보" },
	Version:      "버전",
	Author:       "작성자:",
	License:      "라이선스:",
	VisitWebsite: "웹사이트 방문",
	Close:        "닫기",

	Install: "설치",
	InstallAsk: func(dir string) string {
		return "AltSysInfo가 " + dir + "에 복사되고 시작 메뉴, 바탕 화면, 설치된 앱 목록에 추가됩니다. 이미 설치되어 있으면 업데이트됩니다. 설정은 그대로 유지됩니다.\n\n그런 다음 AltSysInfo가 그곳에서 다시 시작됩니다."
	},
	InstallFailed: func(err string) string { return "AltSysInfo를 설치할 수 없습니다:\n\n" + err },
	Installed:     "AltSysInfo가 설치되었습니다",
	UninstallAsk: func(dir string) string {
		return "이 컴퓨터에서 AltSysInfo를 제거하시겠습니까?\n\n설정은 " + dir + "에 남아 있습니다."
	},
	UninstallRunning: "AltSysInfo가 실행 중입니다. 닫은 후 다시 시도하세요.",
	Uninstalled:      "AltSysInfo가 제거되었습니다.",
}
